
INSERT INTO rs_ceds7_sc.ref_person_relationship( Ref_Person_Relationship_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 1, 'Aunt', 'Aunt', 'The person is the learner''s Aunt.', null, 6.00 ); 
INSERT INTO rs_ceds7_sc.ref_person_relationship( Ref_Person_Relationship_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 2, 'Brother', 'Brother', 'The person is the learner''s Brother.', null, 8.00 ); 
INSERT INTO rs_ceds7_sc.ref_person_relationship( Ref_Person_Relationship_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 3, 'Brother-in-law', 'Brother_In_Law', 'The person is the learner''s Brother-in-law.', null, 10.00 ); 
INSERT INTO rs_ceds7_sc.ref_person_relationship( Ref_Person_Relationship_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 4, 'Court appointed guardian', 'Court_Appointed_Guardian', 'The person is the learner''s court appointed guardian.', null, 11.00 ); 
INSERT INTO rs_ceds7_sc.ref_person_relationship( Ref_Person_Relationship_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 5, 'Daughter', 'Daughter', 'The person is the learner''s Daughter.', null, 13.00 ); 
INSERT INTO rs_ceds7_sc.ref_person_relationship( Ref_Person_Relationship_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 6, 'Daughter-in-law', 'Daughter_In_Law', 'The person is the learner''s Aunt.', null, 14.00 ); 
INSERT INTO rs_ceds7_sc.ref_person_relationship( Ref_Person_Relationship_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 7, 'Employer', 'Employer', 'The person is the learner''s Employer.', null, 16.00 ); 
INSERT INTO rs_ceds7_sc.ref_person_relationship( Ref_Person_Relationship_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 8, 'Father', 'Father', 'The person is the learner''s Father.', null, 17.00 ); 
INSERT INTO rs_ceds7_sc.ref_person_relationship( Ref_Person_Relationship_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 9, 'Father''s significant other', 'Fathers_Significant_Other', 'The person is the significant other of the learner''s Father.', null, 18.00 ); 
INSERT INTO rs_ceds7_sc.ref_person_relationship( Ref_Person_Relationship_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 10, 'Father''s civil partner', 'Fathers_Civil_Partner', 'The person is a legal partner of the learner''s father, established by a civil union other than marriage.', null, 19.00 ); 
INSERT INTO rs_ceds7_sc.ref_person_relationship( Ref_Person_Relationship_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 11, 'Father-in-law', 'Father_In_Law', 'The person is the father of the learner''s spouse.', null, 22.00 ); 
INSERT INTO rs_ceds7_sc.ref_person_relationship( Ref_Person_Relationship_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 12, 'Fiance', 'Fiance', 'The person is  a man who is engaged to be married to the learner.', null, 23.00 ); 
INSERT INTO rs_ceds7_sc.ref_person_relationship( Ref_Person_Relationship_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 13, 'Fiancee', 'Fiancee', 'The person is  a woman who is engaged to be married to the learner.', null, 24.00 ); 
INSERT INTO rs_ceds7_sc.ref_person_relationship( Ref_Person_Relationship_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 14, 'Friend', 'Friend', 'The person is the learner''s Friend.', null, 30.00 ); 
INSERT INTO rs_ceds7_sc.ref_person_relationship( Ref_Person_Relationship_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 15, 'Grandfather', 'Grandfather', 'The person is the learner''s Grandfather.', null, 32.00 ); 
INSERT INTO rs_ceds7_sc.ref_person_relationship( Ref_Person_Relationship_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 16, 'Grandmother', 'Grandmother', 'The person is the learner''s Grandmother.', null, 33.00 ); 
INSERT INTO rs_ceds7_sc.ref_person_relationship( Ref_Person_Relationship_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 17, 'Husband', 'Husband', 'The person is the learner''s Husband.', null, 37.00 ); 
INSERT INTO rs_ceds7_sc.ref_person_relationship( Ref_Person_Relationship_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 18, 'Mother''s significant other', 'Mothers_Significant_Other', 'The person is the significant other of the learner''s Mother.', null, 41.00 ); 
INSERT INTO rs_ceds7_sc.ref_person_relationship( Ref_Person_Relationship_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 19, 'Mother', 'Mother', 'The person is the learner''s Mother', null, 43.00 ); 
INSERT INTO rs_ceds7_sc.ref_person_relationship( Ref_Person_Relationship_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 20, 'Mother''s civil partner', 'Mothers_Civil_Partner', 'The person is a legal partner of the learner''s mother, established by a civil union other than marriage.', null, 44.00 ); 
INSERT INTO rs_ceds7_sc.ref_person_relationship( Ref_Person_Relationship_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 21, 'Nephew', 'Nephew', 'The person is the learner''s Nephew.', null, 46.00 ); 
INSERT INTO rs_ceds7_sc.ref_person_relationship( Ref_Person_Relationship_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 22, 'Niece', 'Niece', 'The person is the learner''s Niece.', null, 47.00 ); 
INSERT INTO rs_ceds7_sc.ref_person_relationship( Ref_Person_Relationship_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 23, 'Other', 'Other', 'The person is related to the learner in a way not represented by other standard options.', null, 49.00 ); 
INSERT INTO rs_ceds7_sc.ref_person_relationship( Ref_Person_Relationship_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 24, 'Significant other', 'Significant_Other', 'The person is the Significant other of the learner.', null, 53.00 ); 
INSERT INTO rs_ceds7_sc.ref_person_relationship( Ref_Person_Relationship_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 25, 'Sister', 'Sister', 'The person is the learner''s Sister.', null, 55.00 ); 
INSERT INTO rs_ceds7_sc.ref_person_relationship( Ref_Person_Relationship_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 26, 'Son', 'Son', 'The person is the learner''s Son.', null, 58.00 ); 
INSERT INTO rs_ceds7_sc.ref_person_relationship( Ref_Person_Relationship_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 27, 'Unknown', 'Unknown', 'The person is the learner''s Unknown.', null, 61.00 ); 
INSERT INTO rs_ceds7_sc.ref_person_relationship( Ref_Person_Relationship_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 28, 'Uncle', 'Uncle', 'The person is the learner''s Uncle.', null, 62.00 ); 
INSERT INTO rs_ceds7_sc.ref_person_relationship( Ref_Person_Relationship_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 29, 'Ward', 'Ward', 'The person is the learner''s Ward.', null, 63.00 ); 
INSERT INTO rs_ceds7_sc.ref_person_relationship( Ref_Person_Relationship_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 30, 'Wife', 'Wife', 'The person is the learner''s Wife.', null, 64.00 ); 

INSERT INTO rs_ceds7_sc.ref_person_telephone_number_type( Ref_Person_Telephone_Number_Type_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 1, 'Home phone number', 'Home', 'Home phone number is the type of communication number listed for a person.', null, 1.00 ); 
INSERT INTO rs_ceds7_sc.ref_person_telephone_number_type( Ref_Person_Telephone_Number_Type_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 2, 'Work phone number', 'Work', 'Work phone number is the type of communication number listed for a person.', null, 3.00 ); 
INSERT INTO rs_ceds7_sc.ref_person_telephone_number_type( Ref_Person_Telephone_Number_Type_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 3, 'Mobile phone number', 'Mobile', 'Mobile phone number is the type of communication number listed for a person.', null, 5.00 ); 
INSERT INTO rs_ceds7_sc.ref_person_telephone_number_type( Ref_Person_Telephone_Number_Type_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 4, 'Fax number', 'Fax', 'Fax number is the type of communication number listed for a person.', null, 7.00 ); 
INSERT INTO rs_ceds7_sc.ref_person_telephone_number_type( Ref_Person_Telephone_Number_Type_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 5, 'Other', 'Other', 'The type of communication number listed for a person is in a category not yet defined in CEDS.', null, 9.00 ); 

INSERT INTO rs_ceds7_sc.ref_population_served( Ref_Population_Served_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 1, 'English language learners', 'ELL', 'The program provides services to meet the needs of English language learners.', null, 1.00 ); 
INSERT INTO rs_ceds7_sc.ref_population_served( Ref_Population_Served_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 2, 'Children with disabilities', 'CWD', 'The program provides services to meet the needs of children with disabilities.', null, 2.00 ); 
INSERT INTO rs_ceds7_sc.ref_population_served( Ref_Population_Served_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 3, 'Homeless', 'Homeless', 'The program provides services to meet the needs of homeless.', null, 4.00 ); 
INSERT INTO rs_ceds7_sc.ref_population_served( Ref_Population_Served_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 4, 'Mental health', 'Mental_Health', 'The program provides mental health services.', null, 5.00 ); 
INSERT INTO rs_ceds7_sc.ref_population_served( Ref_Population_Served_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 5, 'Special health needs', 'Special_Health_Needs', 'The program provides services to meet the needs of learners with special health needs.', null, 6.00 ); 
INSERT INTO rs_ceds7_sc.ref_population_served( Ref_Population_Served_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 6, 'Foster', 'Foster', 'The program provides services to meet the needs of foster children and families.', null, 7.00 ); 
INSERT INTO rs_ceds7_sc.ref_population_served( Ref_Population_Served_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 7, 'Other', 'Other', 'The program provides services to meet the needs of learners in a category not yet defined in CEDS.', null, 10.00 ); 

INSERT INTO rs_ceds7_sc.ref_pre_k_eligible_ages_non_idea( Ref_Pre_K_Eligible_Ages_Non_IDEA_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 1, 'Students aged 0-2', 'Age0-2', 'The Pre_Kindergarten_ program is available to students aged 0-2.', null, 1.00 ); 
INSERT INTO rs_ceds7_sc.ref_pre_k_eligible_ages_non_idea( Ref_Pre_K_Eligible_Ages_Non_IDEA_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 2, 'Students aged 3', 'Age3', 'The Pre_Kindergarten_ program is available to students aged 3.', null, 2.00 ); 
INSERT INTO rs_ceds7_sc.ref_pre_k_eligible_ages_non_idea( Ref_Pre_K_Eligible_Ages_Non_IDEA_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 3, 'Students aged 4', 'Age4', 'The Pre_Kindergarten_ program is available to students aged 4.', null, 3.00 ); 
INSERT INTO rs_ceds7_sc.ref_pre_k_eligible_ages_non_idea( Ref_Pre_K_Eligible_Ages_Non_IDEA_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 4, 'No pre-kindergarten or only for IDEA students', 'No_Pre_K_', 'No pre-kindergarten is available or only for IDEA students.', null, 4.00 ); 

INSERT INTO rs_ceds7_sc.ref_predominant_calendar_system( Ref_Predominant_Calendar_System_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 1, 'Semester ', 'Semester', 'The institution structures most of its courses for the academic year by Semester.', null, 1.00 ); 
INSERT INTO rs_ceds7_sc.ref_predominant_calendar_system( Ref_Predominant_Calendar_System_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 2, 'Quarter ', 'Quarter', 'The institution structures most of its courses for the academic year by Quarter.', null, 2.00 ); 
INSERT INTO rs_ceds7_sc.ref_predominant_calendar_system( Ref_Predominant_Calendar_System_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 3, 'Trimester', 'Trimester', 'The institution structures most of its courses for the academic year by Trimester.', null, 3.00 ); 
INSERT INTO rs_ceds7_sc.ref_predominant_calendar_system( Ref_Predominant_Calendar_System_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 4, '4-1-4 or similar plan', '4-1-4', 'The institution structures most of its courses for the academic year by 4-1-4 or similar plan.', null, 4.00 ); 
INSERT INTO rs_ceds7_sc.ref_predominant_calendar_system( Ref_Predominant_Calendar_System_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 5, 'Other academic plan', 'Other', 'The institution structures most of its courses for the academic year by an academic plan not yet defined in CEDS.', null, 5.00 ); 
INSERT INTO rs_ceds7_sc.ref_predominant_calendar_system( Ref_Predominant_Calendar_System_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 6, 'Differs by program', 'Differs_By_Program', 'The method by which an institution structures most of its courses for the academic year differs by program.', null, 6.00 ); 
INSERT INTO rs_ceds7_sc.ref_predominant_calendar_system( Ref_Predominant_Calendar_System_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 7, 'Continuous basis', 'Continuous_Basis', 'The institution structures most of its courses for the academic year on a continuous basis.', null, 7.00 ); 

INSERT INTO rs_ceds7_sc.ref_professional_development_financial_support( Ref_Professional_Development_Financial_Support_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 1, 'One time non-credit', '01', 'One time financial assistance received in support of the non-credit professional development activity.', null, 1.00 ); 
INSERT INTO rs_ceds7_sc.ref_professional_development_financial_support( Ref_Professional_Development_Financial_Support_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 2, 'One time credit paid', '02', 'One time credit paid in support of the non-credit professional development activity.', null, 2.00 ); 
INSERT INTO rs_ceds7_sc.ref_professional_development_financial_support( Ref_Professional_Development_Financial_Support_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 3, 'On-going non-credit paid', '03', 'On-going non-credit paid in support of the non-credit professional development activity.', null, 3.00 ); 
INSERT INTO rs_ceds7_sc.ref_professional_development_financial_support( Ref_Professional_Development_Financial_Support_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 4, 'On-going credit paid', '04', 'On-going credit paid in support of the non-credit professional development activity.', null, 4.00 ); 
INSERT INTO rs_ceds7_sc.ref_professional_development_financial_support( Ref_Professional_Development_Financial_Support_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 5, 'Salary bonus', '05', 'Salary bonus received in support of the non-credit professional development activity.', null, 5.00 ); 
INSERT INTO rs_ceds7_sc.ref_professional_development_financial_support( Ref_Professional_Development_Financial_Support_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 6, 'Wage enhancement', '06', 'Wage enhancement received in support of the non-credit professional development activity.', null, 6.00 ); 
INSERT INTO rs_ceds7_sc.ref_professional_development_financial_support( Ref_Professional_Development_Financial_Support_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 7, 'Tuition reimbursement', '07', 'Tuition reimbursement received in support of the non-credit professional development activity.', null, 7.00 ); 
INSERT INTO rs_ceds7_sc.ref_professional_development_financial_support( Ref_Professional_Development_Financial_Support_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 8, 'Travel child care', '08', 'Travel child care received in support of the non-credit professional development activity.', null, 8.00 ); 
INSERT INTO rs_ceds7_sc.ref_professional_development_financial_support( Ref_Professional_Development_Financial_Support_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 9, 'Release time', '09', 'Release time received in support of the non-credit professional development activity.', null, 9.00 ); 
INSERT INTO rs_ceds7_sc.ref_professional_development_financial_support( Ref_Professional_Development_Financial_Support_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 10, 'Scholarship', '10', 'Scholarship received in support of the non-credit professional development activity.', null, 10.00 ); 
INSERT INTO rs_ceds7_sc.ref_professional_development_financial_support( Ref_Professional_Development_Financial_Support_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 11, 'Loan', '11', 'Loan received in support of the non-credit professional development activity.', null, 11.00 ); 

INSERT INTO rs_ceds7_sc.ref_professional_technical_credential_type( Ref_Professional_Technical_Credential_Type_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 1, 'Occupational License', 'Occupational_License', 'Occupational License was conferred for competency in a specific area measured by a set of pre-established standards.', null, 1.00 ); 
INSERT INTO rs_ceds7_sc.ref_professional_technical_credential_type( Ref_Professional_Technical_Credential_Type_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 2, 'Industry-recognized Certification', 'Industry_Certification', 'Industry-recognized Certification was conferred for competency in a specific area measured by a set of pre-established standards.', null, 2.00 ); 
INSERT INTO rs_ceds7_sc.ref_professional_technical_credential_type( Ref_Professional_Technical_Credential_Type_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 3, 'Apprenticeship Certificate', 'Apprenticeship_Certificate', 'Apprenticeship Certificate was conferred for competency in a specific area measured by a set of pre-established standards.', null, 3.00 ); 
INSERT INTO rs_ceds7_sc.ref_professional_technical_credential_type( Ref_Professional_Technical_Credential_Type_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 4, 'Employer certification', 'Employer_Certification', 'Employer certification was conferred for competency in a specific area measured by a set of pre-established standards.', null, 5.00 ); 
INSERT INTO rs_ceds7_sc.ref_professional_technical_credential_type( Ref_Professional_Technical_Credential_Type_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 5, 'Pre-employment training certificate', 'Pre_Employment_Training', 'Pre-employment training certificate was conferred for competency in a specific area measured by a set of pre-established standards.', null, 7.00 ); 
INSERT INTO rs_ceds7_sc.ref_professional_technical_credential_type( Ref_Professional_Technical_Credential_Type_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 6, 'Other recognized occupational skills credential', 'Other_Occupational', 'Other recognized occupational skills credential was conferred for competency in a specific area measured by a set of pre-established standards.', null, 9.00 ); 

INSERT INTO rs_ceds7_sc.ref_proficiency_target_ayp( Ref_Proficiency_Target_Ayp_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 1, 'Met: Regular Determination', 'Met', 'The school or district met the proficiency target using the Regular Determination.', null, 1.00 ); 
INSERT INTO rs_ceds7_sc.ref_proficiency_target_ayp( Ref_Proficiency_Target_Ayp_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 2, 'Met: Growth Model ', 'Met_Growth_Model', 'The school or district met the proficiency target using the Growth Model.', null, 2.00 ); 
INSERT INTO rs_ceds7_sc.ref_proficiency_target_ayp( Ref_Proficiency_Target_Ayp_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 3, 'Met Because of Safe Harbor', 'Met_Because_Safe_Harbor', 'The school or district met the proficiency target using the Because of Safe Harbor.', null, 3.00 ); 
INSERT INTO rs_ceds7_sc.ref_proficiency_target_ayp( Ref_Proficiency_Target_Ayp_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 4, 'Did Not Meet Target', 'Did_Not_Meet_Target', 'The school or district did NOT meet the proficiency target.', null, 4.00 ); 
INSERT INTO rs_ceds7_sc.ref_proficiency_target_ayp( Ref_Proficiency_Target_Ayp_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 5, 'Too Few Students for Reliability', 'Too_Few_Students', 'Too Few Students for Reliability.', null, 5.00 ); 
INSERT INTO rs_ceds7_sc.ref_proficiency_target_ayp( Ref_Proficiency_Target_Ayp_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 6, 'No Students in the Sub-group', 'No_Students', 'No Students in the Sub-group.', null, 6.00 ); 
INSERT INTO rs_ceds7_sc.ref_proficiency_target_ayp( Ref_Proficiency_Target_Ayp_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 7, 'Not applicable', 'NA', 'Not applicable.', null, 7.00 ); 

INSERT INTO rs_ceds7_sc.ref_program_day_length( Ref_Program_Day_Length_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 1, 'Full-day', 'Full_Day', 'The program is provided to the students it serves as a full-day program.', null, 1.00 ); 
INSERT INTO rs_ceds7_sc.ref_program_day_length( Ref_Program_Day_Length_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 2, 'Part-day', 'Part-day', 'The program is provided to the students it serves as a part-day program.', null, 2.00 ); 
INSERT INTO rs_ceds7_sc.ref_program_day_length( Ref_Program_Day_Length_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 3, 'Not provided', 'Not_Provided', 'Program is not provided.', null, 3.00 ); 

INSERT INTO rs_ceds7_sc.ref_program_gifted_eligibility( Ref_Program_Gifted_Eligibility_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 1, 'General Intellectual Aptitude only', '13452', 'The student''s eligibility for Gifted/_Talented program is in the category: General Intellectual Aptitude only.', null, 0.00 ); 
INSERT INTO rs_ceds7_sc.ref_program_gifted_eligibility( Ref_Program_Gifted_Eligibility_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 2, 'Specific Academic Aptitude only', '13453', 'The student''s eligibility for Gifted/_Talented program is in the category: Specific Academic Aptitude only.', null, 2.00 ); 
INSERT INTO rs_ceds7_sc.ref_program_gifted_eligibility( Ref_Program_Gifted_Eligibility_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 3, 'Visual/_Performing Arts only', '13454', 'The student''s eligibility for Gifted/_Talented program is in the category: Visual/_Performing Arts only.', null, 4.00 ); 
INSERT INTO rs_ceds7_sc.ref_program_gifted_eligibility( Ref_Program_Gifted_Eligibility_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 4, 'General Intellectual Aptitude & Specific Academic Aptitude', '13456', 'The student''s eligibility for Gifted/_Talented program is in the category: General Intellectual Aptitude & Specific Academic Aptitude.', null, 6.00 ); 
INSERT INTO rs_ceds7_sc.ref_program_gifted_eligibility( Ref_Program_Gifted_Eligibility_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 5, 'General Intellectual Aptitude & Visual/_Performing Arts', '13457', 'The student''s eligibility for Gifted/_Talented program is in the category: General Intellectual Aptitude & Visual/_Performing Arts.', null, 8.00 ); 
INSERT INTO rs_ceds7_sc.ref_program_gifted_eligibility( Ref_Program_Gifted_Eligibility_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 6, 'General Intellectual Aptitude & Technical/_Practical Arts', '13458', 'The student''s eligibility for Gifted/_Talented program is in the category: General Intellectual Aptitude & Technical/_Practical Arts.', null, 10.00 ); 
INSERT INTO rs_ceds7_sc.ref_program_gifted_eligibility( Ref_Program_Gifted_Eligibility_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 7, 'Specific Academic Aptitude & Visual/_Performing Arts', '13459', 'The student''s eligibility for Gifted/_Talented program is in the category: Specific Academic Aptitude & Visual/_Performing Arts.', null, 12.00 ); 
INSERT INTO rs_ceds7_sc.ref_program_gifted_eligibility( Ref_Program_Gifted_Eligibility_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 8, 'Specific Academic Aptitude & Technical/_Practical Arts', '13460', 'The student''s eligibility for Gifted/_Talented program is in the category: Specific Academic Aptitude & Technical/_Practical Arts.', null, 14.00 ); 
INSERT INTO rs_ceds7_sc.ref_program_gifted_eligibility( Ref_Program_Gifted_Eligibility_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 9, 'Visual/_Performing Arts & Technical/_Practical Arts', '13461', 'The student''s eligibility for Gifted/_Talented program is in the category: Visual/_Performing Arts & Technical/_Practical Arts.', null, 16.00 ); 
INSERT INTO rs_ceds7_sc.ref_program_gifted_eligibility( Ref_Program_Gifted_Eligibility_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 10, 'General Intellectual Aptitude, Specific Academic Aptitude, and Visual Performing Arts', '13462', 'The student''s eligibility for Gifted/_Talented program is in the category: General Intellectual Aptitude, Specific Academic Aptitude, and Visual Performing Arts.', null, 18.00 ); 
INSERT INTO rs_ceds7_sc.ref_program_gifted_eligibility( Ref_Program_Gifted_Eligibility_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 11, 'General Intellectual Aptitude, Specific Academic Aptitude, & Technical/_Practical Arts', '13463', 'The student''s eligibility for Gifted/_Talented program is in the category: General Intellectual Aptitude, Specific Academic Aptitude, & Technical/_Practical Arts.', null, 20.00 ); 
INSERT INTO rs_ceds7_sc.ref_program_gifted_eligibility( Ref_Program_Gifted_Eligibility_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 12, 'Specific Academic Aptitude, Visual/_Performing Arts, & Technical/_Practical Arts', '13464', 'The student''s eligibility for Gifted/_Talented program is in the category: Specific Academic Aptitude, Visual/_Performing Arts, & Technical/_Practical Arts.', null, 22.00 ); 
INSERT INTO rs_ceds7_sc.ref_program_gifted_eligibility( Ref_Program_Gifted_Eligibility_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 14, 'Not specified', '06002', 'The student''s eligibility for Gifted/_Talented program is in the category is not specified.', null, 26.00 ); 
INSERT INTO rs_ceds7_sc.ref_program_gifted_eligibility( Ref_Program_Gifted_Eligibility_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 15, 'Other', '09999', 'The student''s eligibility for Gifted/_Talented program is in a category not yet defined in CEDS.', null, 28.00 ); 

INSERT INTO rs_ceds7_sc.ref_program_sponsor_type( Ref_Program_Sponsor_Type_Id, Description, Code, Definition, Ref_Jurisdiction, Sort_Order ) VALUES ( 1, 'Business', 'Business', 'A business is providing funds for a particular educational or service program or activity or for an individual''s participation in the program or activity.', null, 1.00 ); 
INSERT INTO rs_ceds7_sc.ref_program_sponsor_type( Ref_Program_Sponsor_Type_Id, Description, Code, Definition, Ref_Jurisdiction, Sort_Order ) VALUES ( 2, 'Education organization network', 'Education_Organization_Network', 'An education organization network is providing funds for a particular educational or service program or activity or for an individual''s participation in the program or activity.', null, 2.00 ); 
INSERT INTO rs_ceds7_sc.ref_program_sponsor_type( Ref_Program_Sponsor_Type_Id, Description, Code, Definition, Ref_Jurisdiction, Sort_Order ) VALUES ( 3, 'Education Service Center', 'Education_Service_Center', 'An education Service Center is providing funds for a particular educational or service program or activity or for an individual''s participation in the program or activity.', null, 3.00 ); 
INSERT INTO rs_ceds7_sc.ref_program_sponsor_type( Ref_Program_Sponsor_Type_Id, Description, Code, Definition, Ref_Jurisdiction, Sort_Order ) VALUES ( 4, 'Federal government', 'Federal', 'The federal government is providing funds for a particular educational or service program or activity or for an individual''s participation in the program or activity.', null, 4.00 ); 
INSERT INTO rs_ceds7_sc.ref_program_sponsor_type( Ref_Program_Sponsor_Type_Id, Description, Code, Definition, Ref_Jurisdiction, Sort_Order ) VALUES ( 5, 'Local education agency', 'LEA', 'The local education agency is providing funds for a particular educational or service program or activity or for an individual''s participation in the program or activity.', null, 5.00 ); 
INSERT INTO rs_ceds7_sc.ref_program_sponsor_type( Ref_Program_Sponsor_Type_Id, Description, Code, Definition, Ref_Jurisdiction, Sort_Order ) VALUES ( 6, 'Non-profit organization', 'Non_Profit', 'A non-profit organization is providing funds for a particular educational or service program or activity or for an individual''s participation in the program or activity.', null, 7.00 ); 
INSERT INTO rs_ceds7_sc.ref_program_sponsor_type( Ref_Program_Sponsor_Type_Id, Description, Code, Definition, Ref_Jurisdiction, Sort_Order ) VALUES ( 7, 'Postsecondary institution', 'Postsecondary', 'A postsecondary institution is providing funds for a particular educational or service program or activity or for an individual''s participation in the program or activity.', null, 9.00 ); 
INSERT INTO rs_ceds7_sc.ref_program_sponsor_type( Ref_Program_Sponsor_Type_Id, Description, Code, Definition, Ref_Jurisdiction, Sort_Order ) VALUES ( 8, 'Private organization', 'Private', 'A private organization is providing funds for a particular educational or service program or activity or for an individual''s participation in the program or activity.', null, 11.00 ); 
INSERT INTO rs_ceds7_sc.ref_program_sponsor_type( Ref_Program_Sponsor_Type_Id, Description, Code, Definition, Ref_Jurisdiction, Sort_Order ) VALUES ( 9, 'Regional or intermediate education agency', 'Regional', 'A regional or intermediate education agency is providing funds for a particular educational or service program or activity or for an individual''s participation in the program or activity.', null, 13.00 ); 
INSERT INTO rs_ceds7_sc.ref_program_sponsor_type( Ref_Program_Sponsor_Type_Id, Description, Code, Definition, Ref_Jurisdiction, Sort_Order ) VALUES ( 10, 'Religious organization', 'Religious', 'A religious organization is providing funds for a particular educational or service program or activity or for an individual''s participation in the program or activity.', null, 15.00 ); 
INSERT INTO rs_ceds7_sc.ref_program_sponsor_type( Ref_Program_Sponsor_Type_Id, Description, Code, Definition, Ref_Jurisdiction, Sort_Order ) VALUES ( 11, 'School', 'School', 'The school is providing funds for a particular educational or service program or activity or for an individual''s participation in the program or activity.', null, 17.00 ); 
INSERT INTO rs_ceds7_sc.ref_program_sponsor_type( Ref_Program_Sponsor_Type_Id, Description, Code, Definition, Ref_Jurisdiction, Sort_Order ) VALUES ( 12, 'State Education Agency', 'SEA', 'The State Education Agency is providing funds for a particular educational or service program or activity or for an individual''s participation in the program or activity.', null, 19.00 ); 
INSERT INTO rs_ceds7_sc.ref_program_sponsor_type( Ref_Program_Sponsor_Type_Id, Description, Code, Definition, Ref_Jurisdiction, Sort_Order ) VALUES ( 13, 'Other', 'Other', 'The category of organization providing funds for the particular educational or service program or activity or for an individual''s participation in the program or activity is not yet defined in CEDS.', null, 21.00 ); 

INSERT INTO rs_ceds7_sc.ref_progress_level( Ref_Progress_Level_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 1, 'Negative grade level change', 'NEGGRADE', 'The students showed a negative grade level change from the pre- to post- test', null, 1.00 ); 
INSERT INTO rs_ceds7_sc.ref_progress_level( Ref_Progress_Level_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 2, 'No change', 'NOCHANGE', 'The students showed no change from the pre- to post- test', null, 2.00 ); 
INSERT INTO rs_ceds7_sc.ref_progress_level( Ref_Progress_Level_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 3, 'Improvement of up to one half grade level', 'UPHALFGRADE', 'The students showed improvement of up to one half grade level from the pre- to post- test', null, 3.00 ); 
INSERT INTO rs_ceds7_sc.ref_progress_level( Ref_Progress_Level_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 4, 'Improvement from one half grade level up to one full grade level', 'UPONEGRADE', 'The students showed improvement from one half grade level up to one full grade level from the pre- to post- test', null, 4.00 ); 
INSERT INTO rs_ceds7_sc.ref_progress_level( Ref_Progress_Level_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 5, 'Improvement of more than one full grade level', 'UPGTONE', 'The students showed improvement of more than one full grade level from the pre- to post- test', null, 5.00 ); 

INSERT INTO rs_ceds7_sc.ref_proof_of_residency_type( Ref_Proof_Of_Residency_Type_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 1, 'Bank statement', 'Bank_Statement', 'Bank statement was used as proof of residency.', null, 1.00 ); 
INSERT INTO rs_ceds7_sc.ref_proof_of_residency_type( Ref_Proof_Of_Residency_Type_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 2, 'Utility bill', 'Utility_Bill', 'Utility bill was used as proof of residency.', null, 2.00 ); 
INSERT INTO rs_ceds7_sc.ref_proof_of_residency_type( Ref_Proof_Of_Residency_Type_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 3, 'Lease', 'Lease', 'Lease was used as proof of residency.', null, 3.00 ); 
INSERT INTO rs_ceds7_sc.ref_proof_of_residency_type( Ref_Proof_Of_Residency_Type_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 4, 'Other', 'Other', 'Other was used as proof of residency.', null, 4.00 ); 

INSERT INTO rs_ceds7_sc.ref_ps_enrollment_award_type( Ref_Ps_Enrollment_Award_Type_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 1, 'Postsecondary award, certificate, or diploma of less than 1 academic year', '01', 'Postsecondary award, certificate, or diploma of less than 1 academic year is the award level in which the person is currently enrolled.', null, 1.00 ); 
INSERT INTO rs_ceds7_sc.ref_ps_enrollment_award_type( Ref_Ps_Enrollment_Award_Type_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 2, 'Postsecondary award, certificate, or diploma of at least 1 but less than 2 academic years', '02', 'Postsecondary award, certificate, or diploma of at least 1 but less than 2 academic years is the award level in which the person is currently enrolled.', null, 2.00 ); 
INSERT INTO rs_ceds7_sc.ref_ps_enrollment_award_type( Ref_Ps_Enrollment_Award_Type_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 3, 'Associate''s Degree', '03', 'Associate''s Degree is the award level in which the person is currently enrolled.', null, 3.00 ); 
INSERT INTO rs_ceds7_sc.ref_ps_enrollment_award_type( Ref_Ps_Enrollment_Award_Type_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 4, 'Postsecondary award, certificate, or diploma of at least 2 but less than 4 academic  years', '04', 'Postsecondary award, certificate, or diploma of at least 2 but less than 4 academic  years is the award level in which the person is currently enrolled.', null, 4.00 ); 
INSERT INTO rs_ceds7_sc.ref_ps_enrollment_award_type( Ref_Ps_Enrollment_Award_Type_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 5, 'Bachelor''s Degree', '05', 'Bachelor''s Degree is the award level in which the person is currently enrolled.', null, 5.00 ); 
INSERT INTO rs_ceds7_sc.ref_ps_enrollment_award_type( Ref_Ps_Enrollment_Award_Type_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 6, 'Postbaccalaureate Certificate', '06', 'Postbaccalaureate Certificate is the award level in which the person is currently enrolled.', null, 6.00 ); 
INSERT INTO rs_ceds7_sc.ref_ps_enrollment_award_type( Ref_Ps_Enrollment_Award_Type_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 7, 'Master''s Degree', '07', 'Master''s Degree is the award level in which the person is currently enrolled.', null, 7.00 ); 
INSERT INTO rs_ceds7_sc.ref_ps_enrollment_award_type( Ref_Ps_Enrollment_Award_Type_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 8, 'Post-master''s certificate', '08', 'Post-master''s certificate is the award level in which the person is currently enrolled.', null, 8.00 ); 
INSERT INTO rs_ceds7_sc.ref_ps_enrollment_award_type( Ref_Ps_Enrollment_Award_Type_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 9, 'Doctor''s Degree-Research/_Scholarship', '17', 'Doctor''s Degree-Research/_Scholarship is the award level in which the person is currently enrolled.', null, 9.00 ); 
INSERT INTO rs_ceds7_sc.ref_ps_enrollment_award_type( Ref_Ps_Enrollment_Award_Type_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 10, 'Doctor''s Degree-Professional Practice', '18', 'Doctor''s Degree-Professional Practice is the award level in which the person is currently enrolled.', null, 10.00 ); 
INSERT INTO rs_ceds7_sc.ref_ps_enrollment_award_type( Ref_Ps_Enrollment_Award_Type_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 11, 'Doctor''s Degree-Other', '19', 'Doctor''s Degree-Other is the award level in which the person is currently enrolled.', null, 11.00 ); 

INSERT INTO rs_ceds7_sc.ref_ps_enrollment_type( Ref_Ps_Enrollment_Type_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 1, 'First time at institution, non-transfer in', 'First_Time', 'The person''s enrollment type associated with the enrollment award level at the beginning of a term is: First time at institution, non-transfer in.', null, 1.00 ); 
INSERT INTO rs_ceds7_sc.ref_ps_enrollment_type( Ref_Ps_Enrollment_Type_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 2, 'Continuing', 'Continuing', 'The person''s enrollment type associated with the enrollment award level at the beginning of a term is: Continuing.', null, 2.00 ); 
INSERT INTO rs_ceds7_sc.ref_ps_enrollment_type( Ref_Ps_Enrollment_Type_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 3, 'Re-admit', 'Re-admit', 'The person''s enrollment type associated with the enrollment award level at the beginning of a term is: Re-admit.', null, 3.00 ); 
INSERT INTO rs_ceds7_sc.ref_ps_enrollment_type( Ref_Ps_Enrollment_Type_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 4, 'Transfer in', 'Transfer_In', 'The person''s enrollment type associated with the enrollment award level at the beginning of a term is: Transfer in.', null, 4.00 ); 

INSERT INTO rs_ceds7_sc.ref_ps_exit_or_withdrawal_type( Ref_PS_Exit_Or_Withdrawal_Type_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 1, 'Withdrawn', 'Withdrawn', 'A student enrolled in a postsecondary institution who has withdrawn, dropped out, failed to re-enroll or been terminated, expelled or dismissed by the institution is considered withdrawn.', null, 1.00 ); 
INSERT INTO rs_ceds7_sc.ref_ps_exit_or_withdrawal_type( Ref_PS_Exit_Or_Withdrawal_Type_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 2, 'Graduated', 'Graduated', 'A student who was enrolled in an eligible postsecondary institution and completed the requirements for graduation or the program of study in which he/she was enrolled is considered graduated.', null, 3.00 ); 
INSERT INTO rs_ceds7_sc.ref_ps_exit_or_withdrawal_type( Ref_PS_Exit_Or_Withdrawal_Type_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 3, 'Approved Leave of Absence', 'Approved_Leave_Of_Absence', 'A student who is enrolled in an eligible postsecondary institution and has met the requirements for an approved student loan leave of absence and, therefore, is not required to attend classes for a specified period of time. For purposes of Title IV, HEA program loan borrower, an institution does not have to treat a leave of absence as a withdrawal if it is an approved leave of absence. An approved student loan leave of absence must not exceed 180 days in any 12-month-period. The number of days in a leave of absence is counted beginning with the first day of the student?s initial leave of absence in a 12-month period. If a student does not resume attendance at the institution at or before the end of a leave of absence, the institution must treat the student as a withdrawal in accordance with CFR 668.22(d).', null, 5.00 ); 
INSERT INTO rs_ceds7_sc.ref_ps_exit_or_withdrawal_type( Ref_PS_Exit_Or_Withdrawal_Type_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 4, 'Deceased', 'Deceased', 'Student is deceased.', null, 7.00 ); 
INSERT INTO rs_ceds7_sc.ref_ps_exit_or_withdrawal_type( Ref_PS_Exit_Or_Withdrawal_Type_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 5, 'Unknown', 'Unknown', 'Student''s exit circumstances are unknown.', null, 9.00 ); 

INSERT INTO rs_ceds7_sc.ref_ps_student_level( Ref_Ps_Student_Level_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 1, 'Undergraduate', 'Undergraduate', 'The person enrolling in credit-granting courses at the postsecondary institution is at the undergraduate level.', null, 1.00 ); 
INSERT INTO rs_ceds7_sc.ref_ps_student_level( Ref_Ps_Student_Level_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 2, 'Graduate', 'Graduate', 'The person enrolling in credit-granting courses at the postsecondary institution is at the graduate level.', null, 2.00 ); 

INSERT INTO rs_ceds7_sc.ref_public_school_residence( Ref_Public_School_Residence_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 1, 'Resident of administrative unit and usual school attendance area', '01652', 'The person is/was a resident of administrative unit and usual school attendance area.', null, 1.00 ); 
INSERT INTO rs_ceds7_sc.ref_public_school_residence( Ref_Public_School_Residence_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 2, 'Resident of administrative unit, but of other school attendance area', '01653', 'The person is/was a resident of administrative unit, but of other school attendance area.', null, 2.00 ); 
INSERT INTO rs_ceds7_sc.ref_public_school_residence( Ref_Public_School_Residence_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 3, 'Resident of this state, but not of this administrative unit', '01654', 'The person is/was a resident of this state, but not of this administrative unit.', null, 3.00 ); 
INSERT INTO rs_ceds7_sc.ref_public_school_residence( Ref_Public_School_Residence_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 4, 'Resident of an administrative unit that crosses state boundaries', '01655', 'The person is/was a resident of an administrative unit that crosses state boundaries.', null, 4.00 ); 
INSERT INTO rs_ceds7_sc.ref_public_school_residence( Ref_Public_School_Residence_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 5, 'Resident of another state', '01656', 'The person is/was a resident of another state.', null, 5.00 ); 

INSERT INTO rs_ceds7_sc.ref_qris_participation( Ref_Qris_Participation_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 1, 'Yes', 'Yes', 'Yes: Provider does participate in the QRIS', null, 1.00 ); 
INSERT INTO rs_ceds7_sc.ref_qris_participation( Ref_Qris_Participation_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 2, 'No', 'No', 'No: Provider is eligible, but does not participate in the QRIS', null, 2.00 ); 
INSERT INTO rs_ceds7_sc.ref_qris_participation( Ref_Qris_Participation_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 3, 'Not Eligible', 'Not_Eligible', 'The State has an operating QRIS in the provider?s area, but the provider is not eligible to participate', null, 3.00 ); 
INSERT INTO rs_ceds7_sc.ref_qris_participation( Ref_Qris_Participation_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 4, 'No Operating QRIS', 'No_Operating_QRIS', 'The State does not have an operating QRIS in the provider?s area', null, 4.00 ); 
INSERT INTO rs_ceds7_sc.ref_qris_participation( Ref_Qris_Participation_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 5, 'Information Unavailable', 'Information_Unavailable', 'The State has an operating QRIS in the provider?s area, but information is currently unavailable at the provider level', null, 5.00 ); 

INSERT INTO rs_ceds7_sc.ref_reap_alternative_funding_status( Ref_Reap_Alternative_Funding_Status_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 1, 'Yes', 'Yes', null, null, 1.00 ); 
INSERT INTO rs_ceds7_sc.ref_reap_alternative_funding_status( Ref_Reap_Alternative_Funding_Status_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 2, 'No', 'No', null, null, 2.00 ); 
INSERT INTO rs_ceds7_sc.ref_reap_alternative_funding_status( Ref_Reap_Alternative_Funding_Status_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 3, 'Not applicable', 'NA', null, null, 3.00 ); 

INSERT INTO rs_ceds7_sc.ref_reconstituted_status( Ref_Reconstituted_Status_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 1, 'Reconstituted school', 'Yes', null, null, 1.00 ); 
INSERT INTO rs_ceds7_sc.ref_reconstituted_status( Ref_Reconstituted_Status_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 2, 'Not a reconstituted school', 'No', null, null, 2.00 ); 

INSERT INTO rs_ceds7_sc.ref_reimbursement_type( Ref_Reimbursement_Type_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 1, 'Fee for Service', 'Fee_For_Service', 'Reimbursed via fee for service.', null, 1.00 ); 
INSERT INTO rs_ceds7_sc.ref_reimbursement_type( Ref_Reimbursement_Type_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 2, 'Capitated Rate', 'Capitated_Rate', 'Reimbursed via capitated rate.', null, 3.00 ); 
INSERT INTO rs_ceds7_sc.ref_reimbursement_type( Ref_Reimbursement_Type_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 3, 'Grant/contract', 'Grant_Contract', 'Reimbursed via grant/contract.', null, 5.00 ); 
INSERT INTO rs_ceds7_sc.ref_reimbursement_type( Ref_Reimbursement_Type_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 4, 'Subsidy', 'Subsidy', 'Reimbursed via subsidy.', null, 7.00 ); 
INSERT INTO rs_ceds7_sc.ref_reimbursement_type( Ref_Reimbursement_Type_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 5, 'Other', 'Other', 'The reimbursement type is in a category not yet defined in CEDS.', null, 9.00 ); 

INSERT INTO rs_ceds7_sc.ref_rlis_program_use( Ref_Rlis_Program_Use_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 1, 'Teacher recruitment and retention', '01', 'Teacher recruitment and retention, including the use of signing bonuses and other financial incentives', null, 1.00 ); 
INSERT INTO rs_ceds7_sc.ref_rlis_program_use( Ref_Rlis_Program_Use_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 2, 'Teacher professional development', '02', 'Teacher professional development, including programs that train teachers to utilize technology to improve teaching and to train special needs teachers', null, 2.00 ); 
INSERT INTO rs_ceds7_sc.ref_rlis_program_use( Ref_Rlis_Program_Use_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 3, 'Educational technology', '03', 'Educational technology, including software and hardware as described in Title II, Part D', null, 3.00 ); 
INSERT INTO rs_ceds7_sc.ref_rlis_program_use( Ref_Rlis_Program_Use_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 4, 'Parental involvement activities', '04', 'Parental involvement activities uses of the Rural Low-Income Schools Program (RLIS) (Title VI, Part B, Subpart 2) Grant Funds.', null, 4.00 ); 
INSERT INTO rs_ceds7_sc.ref_rlis_program_use( Ref_Rlis_Program_Use_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 5, 'Activities authorized under the Safe and Drug-Free Schools Program (Title IV, Part A)', '05', 'Activities authorized under the Safe and Drug-Free Schools Program (Title IV, Part A) using the Rural Low-Income Schools Program (RLIS) (Title VI, Part B, Subpart 2) Grant Funds.', null, 5.00 ); 
INSERT INTO rs_ceds7_sc.ref_rlis_program_use( Ref_Rlis_Program_Use_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 6, 'Activities authorized under Title I, Part A', '06', 'Activities authorized under Title I, Part A using the Rural Low-Income Schools Program (RLIS) (Title VI, Part B, Subpart 2) Grant Funds.', null, 6.00 ); 
INSERT INTO rs_ceds7_sc.ref_rlis_program_use( Ref_Rlis_Program_Use_Id, Description, Code, Definition, Ref_Jurisdiction_Id, Sort_Order ) VALUES ( 7, 'Activities authorized under Title III (Language instruction for LEP and immigrant students)', '07', 'Activities authorized under Title III (Language instruction for LEP and immigrant students) using the Rural Low-Income Schools Program (RLIS) (Title VI, Part B, Subpart 2) Grant Funds.', null, 7.00 ); 

